# Compila el manuscrito de la carpeta que lo incluya. La clase oficial vive en ../plantilla.
TEXINPUTS := ../plantilla:
BSTINPUTS := ../plantilla:
export TEXINPUTS BSTINPUTS

main.pdf: main.tex referencias.bib
	pdflatex -interaction=nonstopmode -halt-on-error main.tex
	-bibtex main
	pdflatex -interaction=nonstopmode -halt-on-error main.tex
	pdflatex -interaction=nonstopmode -halt-on-error main.tex

limpio:
	rm -f main.aux main.bbl main.blg main.log main.out main.spl

.PHONY: limpio
